package generator

@main def generateIconsCode() =
  val icons = Seq(
    "AddIcon",
    "ArrowBackIcon",
    "ArrowDownIcon",
    "ArrowForwardIcon",
    "ArrowLeftIcon",
    "ArrowRightIcon",
    "ArrowUpIcon",
    "ArrowUpDownIcon",
    "AtSignIcon",
    "AttachmentIcon",
    "BellIcon",
    "CalendarIcon",
    "ChatIcon",
    "CheckIcon",
    "CheckCircleIcon",
    "ChevronDownIcon",
    "ChevronLeftIcon",
    "ChevronRightIcon",
    "ChevronUpIcon",
    "CloseIcon",
    "CopyIcon",
    "DeleteIcon",
    "DownloadIcon",
    "DragHandleIcon",
    "EditIcon",
    "EmailIcon",
    "ExternalLinkIcon",
    "HamburgerIcon",
    "InfoIcon",
    "InfoOutlineIcon",
    "LinkIcon",
    "LockIcon",
    "MinusIcon",
    "MoonIcon",
    "NotAllowedIcon",
    "PhoneIcon",
    "PlusSquareIcon",
    "QuestionIcon",
    "QuestionOutlineIcon",
    "RepeatIcon",
    "RepeatClockIcon",
    "SearchIcon",
    "Search2Icon",
    "SettingsIcon",
    "SmallAddIcon",
    "SmallCloseIcon",
    "SpinnerIcon",
    "StarIcon",
    "SunIcon",
    "TimeIcon",
    "TriangleDownIcon",
    "TriangleUpIcon",
    "UnlockIcon",
    "UpDownIcon",
    "ViewIcon",
    "ViewOffIcon",
    "WarningIcon",
    "WarningTwoIcon"
  )

  println("// ------------------------ SCALA CODE -------------------------------------")
  for clz <- icons do println(s"""
        |/** generated by generateIconsCode() , https://chakra-ui.com/docs/components/icon
        | */
        |case class $clz(
        |    key: String = Keys.nextKey,
        |    @volatile var w: Option[String] = None,
        |    @volatile var h: Option[String] = None,
        |    @volatile var boxSize: Option[String] = None,
        |    @volatile var color: Option[String] = None
        |) extends ChakraElement
        |
        |""".stripMargin)
  println("// ------------------------ SCALA USING CODE -------------------------------------")
  println(icons.map(i => s"$i()").mkString(","))
  println("// ------------------------ TSX CODE -------------------------------------")
  println(s"import { ${icons.mkString(",")} } from '@chakra-ui/icons';")
  for clz <- icons do println(s"$clz: (b:any) => (<$clz {...b}/>),")
